### ISSUE TITLE
[Bug]: nexusmods upload command

### ISSUE THREAD

**Issue by Vodianoi** [Digitalroot-Valheim/Digitalroot.ModUploader#10]
### What happened?

Hi !

Got an issue using the nexusmods upload command, it seems 'valheim' is not recognized or something.
I run it in js github action environment : 

```   
 // Upload mod to NexusMods
    await exec('opmu', ['nexusmods', 'check', `-k`, `${apiKey}`, `-cnxid`, `${cookieNexusId}`, `-csid`, `${cookieSidDevelop}`])
    .then(() => exec('opmu', ['nexusmods', 'upload', `${modId}`, `${archiveFile}`, `-f`, `${fileName}-${version}`, `-v`, `${version}`, `-t`, `${category}`,`-d`, `"${description}"`, `-g`, `'${game}'`]))
    .catch((error) => core.setFailed(error));
```
Which provide in log :
`/home/runner/.dotnet/tools/opmu nexusmods upload 2033 QuickPing/QuickPing.zip -f QuickPing-1.5.2 -v 1.5.2 -t Main -d "Ping what you see and pin it on the map !" -g valheim`

The `check` command run successfully

Maybe this repo wasn't supposed to be used yet ?

### Relevant log output

```shell
Attempting to retrieve game details for 'valheim'
Error: Object reference not set to an instance of an object.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RestSharp.HttpRequestMessageExtensions.<AddHeaders>g__AddHeader|0_2(Parameter parameter, HttpHeaders httpHeaders)
   at RestSharp.HttpRequestMessageExtensions.<>c__DisplayClass0_0.<AddHeaders>b__1(Parameter x)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.HttpRequestMessageExtensions.AddHeaders(HttpRequestMessage message, RequestHeaders headers)
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
Preparing to upload 'QuickPing.zip' (100.7KB) as version 1.5.2 to Nexus Mods upload Api.
Attempting to retrieve mod file details for mod '2033' of 'valheim'
Error: Object reference not set to an instance of an object.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RestSharp.HttpRequestMessageExtensions.<AddHeaders>g__AddHeader|0_2(Parameter parameter, HttpHeaders httpHeaders)
   at RestSharp.HttpRequestMessageExtensions.<>c__DisplayClass0_0.<AddHeaders>b__1(Parameter x)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.HttpRequestMessageExtensions.AddHeaders(HttpRequestMessage message, RequestHeaders headers)
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
Can you point me at your failed run to review? try w/o the `-g` part. It defaults to Valheim. I'll look into why `-g` is not working.

**Comment by Vodianoi** [comment]
[Here](https://github.com/Vodianoi/QuickPingMod/actions/runs/3752351109/jobs/6374668447)
I'll try without the `-g` part

**Comment by Vodianoi** [comment]
Same error without `-g`

```
Attempting to retrieve game details for 'valheim'
Error: Object reference not set to an instance of an object.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RestSharp.HttpRequestMessageExtensions.<AddHeaders>g__AddHeader|0_2(Parameter parameter, HttpHeaders httpHeaders)
   at RestSharp.HttpRequestMessageExtensions.<>c__DisplayClass0_0.<AddHeaders>b__1(Parameter x)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.HttpRequestMessageExtensions.AddHeaders(HttpRequestMessage message, RequestHeaders headers)
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
Preparing to upload 'QuickPing.zip' (100.7KB) as version 1.5.2 to Nexus Mods upload Api.
Attempting to retrieve mod file details for mod '2033' of 'valheim'
Error: Object reference not set to an instance of an object.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RestSharp.HttpRequestMessageExtensions.<AddHeaders>g__AddHeader|0_2(Parameter parameter, HttpHeaders httpHeaders)
   at RestSharp.HttpRequestMessageExtensions.<>c__DisplayClass0_0.<AddHeaders>b__1(Parameter x)
   at RestSharp.Extensions.CollectionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at RestSharp.HttpRequestMessageExtensions.AddHeaders(HttpRequestMessage message, RequestHeaders headers)
   at RestSharp.RestClient.ExecuteInternal(RestRequest request, CancellationToken cancellationToken)
```

Here's the [run](https://github.com/Vodianoi/QuickPingMod/actions/runs/3752681406/jobs/6375138306)

There might be an issue with the way I am calling the command. I will check on my end.

**Comment by Digitalroot** [comment]
Here is what I run. 
`opmu nx upload 1538 /home/runner/work/Digitalroot.Valheim.ForsakenJVL/Digitalroot.Valheim.ForsakenJVL/Digitalroot.Valheim.ForsakenJVL.v2.0.2.zip -v 2.0.2 -d "OdinPlusModUploader (CI/CD)" -f Digitalroot.Valheim.ForsakenJVL -dmv`

Here is how I call it in the workflow. 
https://github.com/Digitalroot-Valheim/.github/blob/main/.github/workflows/nuget.release.yml#L511

**Comment by Vodianoi** [comment]
Worked running command directly in yml as you did. Need to figure out what's happening in js...

[EDIT] Find out I just had to specify -k, -cnxid and -csid, since it is not found in Env

Thank you for your answer !
Awesome mods btw !
