### ISSUE TITLE
[Bug]: NRE after upload to Nexus (resulting in no file added to mod)

### ISSUE THREAD

**Issue by spacechase0** [Digitalroot-Valheim/Digitalroot.ModUploader#16]
### How are you playing the game?

Single Player - No Server

### What happened?

I managed to get this working in my github workflow for the most part, but after the file is uploaded to Nexus (from what I can tell, anyways) I get this "Object reference not set to an instance of an object" error. Checking the Nexus mod shows that no new files are uploaded.

Full action log: https://github.com/spacechase0/TestModWorkflow/actions/runs/8461759142/job/23182128194

### To Reproduce

See https://github.com/spacechase0/TestModWorkflow/blob/main/.github/workflows/build-mods.yml

### Relevant log output

```shell
One or more errors occurred. (Object reference not set to an instance of an object.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Digitalroot.ModUploader.Provider.NexusMods.Commands.UploadCommand.AddFileToMod(String cookiesid_develop, UInt32 modId, String version, Boolean disableVersionUpdate, Boolean disableMainVortex, String fileName, FileInfo archiveFile, CategoryName categoryName, String description, Boolean disableDownloadWithManager, Boolean disableRequirementsPopUp, Int32 gameId, String fileUuid, String uploadedFileHash, Boolean disableMainFileUpdate, Int32 oldFileId, Boolean newExisting, Boolean removeOldVersion) in /home/runner/work/Digitalroot.ModUploader/Digitalroot.ModUploader/src/Digitalroot.ModUploader/Provider/NexusMods/Commands/UploadCommand.cs:line 432
   at Digitalroot.ModUploader.Provider.NexusMods.Commands.UploadCommand.<>c__DisplayClass3_0.<<GetCommandHandler>g__RunUploadWorkFlow|1>d.MoveNext() in /home/runner/work/Digitalroot.ModUploader/Digitalroot.ModUploader/src/Digitalroot.ModUploader/Provider/NexusMods/Commands/UploadCommand.cs:line 197
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alcmoe** [comment]
used your workflow example and got same issue :(

**Comment by Digitalroot** [comment]
When this happens to me, Sometimes rerunning the "failed" jobs for a workflow will resolve it. 

**What I think is happening.** 
1. File is broken up into chunks, 
1. Each chunk is uploaded, 
1. Nx reassembles the chunks.
1. ModUploader waits for the reassemble to complete.
1. Assembled file is attached to the mod page. 

There are a few reasons this process can fail. What I have observed, is on a subsequent runs for the same file, nx will report that it already has the chunks of data.  Rerunning only the failed steps of the workflow, will allow it to complete. 

![image](https://github.com/Digitalroot-Valheim/Digitalroot.ModUploader/assets/3770289/e2fb9739-0c18-44b3-bb7f-78818bf27c78)


I have also used this when the session_id times out. I can update the session_id and rerun the failed steps.

**Comment by Digitalroot** [comment]
Maybe the result payload changed. Let me look at it.

**Comment by Digitalroot** [comment]
Still looking at this.

**Comment by khanshoaib3** [comment]
I had the same issue ([here](https://github.com/khanshoaib3/stardew-access/actions/runs/8957894883/job/24601508179)), and the issue seems to be causing because I didn't specified the description of the file.
After specifying the description, the workflow ran as expected ([here](https://github.com/khanshoaib3/stardew-access/actions/runs/8971711731/job/24638075923#step:9:85)).

**Comment by Digitalroot** [comment]
Thanks for the update
